INSERT INTO formulas VALUES("проекция перемещения на ось X","s_x=x+x_0");
INSERT INTO formulas VALUES("скорость равномерного прямолинейного движения","\vec{&upsilon;}=\frac{\vec{s}}{t}");
INSERT INTO formulas VALUES("средняя скорость","&upsilon;_{ср}=\frac{s}{t}");
INSERT INTO formulas VALUES("уравнение равномерного прямолинейного движения","x=x_0+&upsilon;_xt");
INSERT INTO formulas VALUES("ускорение при равноускоренном движении","\vec{a}=\frac{\vec{&upsilon;}-{\vec{&upsilon;_0}}}{t}");
INSERT INTO formulas VALUES("скорость при равноускоренном движении","\vec{&upsilon;}=\vec{&upsilon;_0}-\vec{a}t");
INSERT INTO formulas VALUES("перемещение при равноускоренном движении","\vec{s}=\frac{\vec{&upsilon;}+\vec{&upsilon;_0}}{2}t");
INSERT INTO formulas VALUES("проекция перемещения при равноускоренном движении от времени","\vec{s}=\vec{&upsilon;_0}t+\frac{\vec{a}t^2}{2}");
INSERT INTO formulas VALUES("проекция перемещения при равноускоренном движении без времени","s_x=\frac{&upsilon;_x^2-&upsilon;_{0x}^2}{2a_x}");
INSERT INTO formulas VALUES("уравнение равноускоренного движения","x=x_0+&upsilon;_0t+\frac{at^2}{2}");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("частота обраения","T=\frac{t}{N}");
INSERT INTO formulas VALUES("период ображения","&nu; = \frac{N}{t}");
INSERT INTO formulas VALUES("связь между периодом и частотой обращения","T = \frac{1}{&nu;}");
INSERT INTO formulas VALUES("линейная скорость","&upsilon; = \frac{s}{t}");
INSERT INTO formulas VALUES("линейная скорость, выраженная через период обращения","&upsilon; = \frac{2\pi r}{T}");
INSERT INTO formulas VALUES("линейная скорость, выраженная через частоту обращения","&upsilon; = 2 \pi r &nu;");
INSERT INTO formulas VALUES("угловая скорость","\omega = \frac{\varphi}{t}");
INSERT INTO formulas VALUES("угловая скорость, выраженная через период обращения","\omega = 2 \pi &nu;");
INSERT INTO formulas VALUES("формула связи между линейной и угловой скоростью ","&nu; = \omega r");
INSERT INTO formulas VALUES("центростремительное ускорение, выраженное через линейную скорость = \frac{&upsilon;^2}{r}");
INSERT INTO formulas VALUES("центростремительное ускорение, выраженное через угловую скорость","a = \omega^2 r");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("второй закон Ньютона","\vec{a} = \frac{\vec{F_R}}{m}");
INSERT INTO formulas VALUES("третий закон Ньютона","\vec{F_1} = -\vec{F_2}");
INSERT INTO formulas VALUES("модуль силы трения","F_{тр} = &mu;N");
INSERT INTO formulas VALUES("проекция силы упругости","F_{упр x} = -kx");
INSERT INTO formulas VALUES("сила тяжести","\vec{F} = m\vec{g}");
INSERT INTO formulas VALUES("вес тела на неподвижной или равномерно движущейся опоре(подвесе)","\vec{P} = m\vec{g}");
INSERT INTO formulas VALUES("вес тела на опоре(подвесе)Б движущейся с ускорением","\vec{P} = m(\vec{g}-\vec{a})");
INSERT INTO formulas VALUES("закон всемирного тяготения","F = G\frac{m_1m_2}{r^2}");
INSERT INTO formulas VALUES("ускорения свободного падения","g = G\frac{M}{(R+h)^2}");
INSERT INTO formulas VALUES("1-я космическая скорость","&upsilon; = \sqrt{G\frac{M}{R}}");
INSERT INTO formulas VALUES("второй закон Ньютона в импульсной форме","\vec{F}t = m\vec{&upsilon;}-m\vec{&upsilon;_0}");
INSERT INTO formulas VALUES("закон сохранения импулься двух тел","m_1\vec{&upsilon;_1} +m_2\vec{&upsilon;_2} = m_1\vec{{&upsilon;_1}^\prime} +m_2\vec{{&upsilon;_2}^\prime}");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("момент силы относительно оси вращения ","M = Fd");
INSERT INTO formulas VALUES("условие равновесия тела, не имеющего оси вращения","\sum_{i=1}^m \vec{F}_i = \vec{0}");
INSERT INTO formulas VALUES("условие равновесия тела, имеющего ось вращения","\sum_{i=1}^n M_i = 0");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("плотность вещества","&rho; = \frac{m}{V}");
INSERT INTO formulas VALUES("давление","p = \frac{F}{S}");
INSERT INTO formulas VALUES("зависимость давления жидкости от высоты ее столба","p = &rho;gh");
INSERT INTO formulas VALUES("сила давления жидкости на дно сосуда","F_{дно} = &rho;gHS_{дно}");
INSERT INTO formulas VALUES("сила давления жидкости на боковую поверхность сосуда","F_{бок} = \frac{1}{2}&rho;gHS_{бок}");
INSERT INTO formulas VALUES("закон сообщающихся сосудов для разнородных жидкостей","\frac{h_1}{h_2} = \frac{&rho;_1}{&rho;_2}");
INSERT INTO formulas VALUES("закон Архимеда","F_a = &rho;gV");
INSERT INTO formulas VALUES("формула связи модулей сил, действующих на поршни гидравлической машины","F_2 = F_1 \frac{S_2}{S_1}");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("работа постоянной силы","A = FS\cdot\cos\cdot\alpha");
INSERT INTO formulas VALUES("работа силы трения","A = -F_{тр}s");
INSERT INTO formulas VALUES("работа силы тяжести","A = mg(h_1 - h_2)");
INSERT INTO formulas VALUES("работа силы упругости","A = \frac{k}{2}(x_1^2 - x_2^2)");
INSERT INTO formulas VALUES("мощность при равномерном прямолинейном движении","N = F &upsilon;");
INSERT INTO formulas VALUES("мощность "," N = \frac{A}{t}");
INSERT INTO formulas VALUES("кинетическая энергия тела","E_к = \frac{m&upsilon;^2}{2}");
INSERT INTO formulas VALUES("потенциальная энергия тела","E_п = mgh");
INSERT INTO formulas VALUES("потенциальная энергия упруго деформированного тела","E_п = \frac{kx_2}{2}");
INSERT INTO formulas VALUES("полная механическая энергия замкнутой системы тел","E = E_п + E_к = const");
INSERT INTO formulas VALUES("теорема о кинетической энергии тела","A = \frac{m&upsilon;_2^2}{2} - \frac{m&upsilon;_1^2}{2}");
INSERT INTO formulas VALUES("КПД ","&#951 = \frac{A_п}{A}");
INSERT INTO formulas VALUES("КПД ","&#951 = \frac{N_п}{N}");
INSERT INTO formulas VALUES("x = A\sin (\omega t +&phi;_0)");
INSERT INTO formulas VALUES("&upsilon;_x = &upsilon;_m \cos(\omega t +&phi;_0)");
INSERT INTO formulas VALUES("a_x = -a_m \sin(\omega t + +&phi;_0)");
INSERT INTO formulas VALUES("\omega = 2 \pi &nu; = \frac{2\pi}{T}");
INSERT INTO formulas VALUES("T = \frac{1}{T}");
INSERT INTO formulas VALUES("&nu; = \frac{1}{T}");
INSERT INTO formulas VALUES("&upsilon;_m = \omega A");
INSERT INTO formulas VALUES("a_m = -\omega^2 A");
INSERT INTO formulas VALUES("T = 2\pi \sqrt{\frac{m}{k}}");
INSERT INTO formulas VALUES("T = 2\pi \sqrt{\frac{l}{g}}");
INSERT INTO formulas VALUES("\frac{kA^2}{2} = \frac{m&upsilon;_x^2}{2} + \frac{kx^2}{2} = \frac{m&upsilon;_m^2}{2}");
INSERT INTO formulas VALUES("\lambda =&upsilon;T");
INSERT INTO formulas VALUES("\nu = \frac{N}{N_A} = \frac{m}{M}");
INSERT INTO formulas VALUES("M = m_o N_A");
INSERT INTO formulas VALUES("p = \frac{1}{3}nm_o\vec{&upsilon;}^2");
INSERT INTO formulas VALUES("p = \frac{2}{3}n\overline{E}");
INSERT INTO formulas VALUES("p = nkt");
INSERT INTO formulas VALUES("\overline{E} = \frac{3}{2}kT");
INSERT INTO formulas VALUES("&upsilon; = \sqrt{\frac{3RT}{M}}");
INSERT INTO formulas VALUES("\frac{pV}{T} = const");
INSERT INTO formulas VALUES("pV = \frac{m}{M}RT");
INSERT INTO formulas VALUES("pv =const при T = const");
INSERT INTO formulas VALUES("\frac VT = при p = const");
INSERT INTO formulas VALUES("\frac pT = const при V = const");
INSERT INTO formulas VALUES("\[U = \frac i2 \frac mM RT\]");
INSERT INTO formulas VALUES("\[Q = cm(t_2-t_1)\]");
INSERT INTO formulas VALUES("\[C = cm\]");
INSERT INTO formulas VALUES("\[Q_п = rm\]");
INSERT INTO formulas VALUES("\[Q_{пл} = \lambda m\]");
INSERT INTO formulas VALUES("\[A' = p\Delta V\]");
INSERT INTO formulas VALUES("\[Q = \Delta U +A'\]");
INSERT INTO formulas VALUES("\[\sum_{i=1}^n Q_i = 0\]");
INSERT INTO formulas VALUES("\[&#951 = \frac{T_1 - T_2}{T-1}\]");
INSERT INTO formulas VALUES("\[&#951 = \frac{Q_1 - Q_2}{Q_1}\]");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("закон Кулона ","F = k \frac{\vert q_1  \vert q_2}{&epsilon; r^2}");
INSERT INTO formulas VALUES("коэфицент пропорциальнсоти ","k = \frac{1}{4\pi &epsilon;_0} = 9 \cdot10^9 \frac{&Iota; \cdot \iota}{\vert E \vert ё^2}");
INSERT INTO formulas VALUES("напряженность электростатического поля","\vec E = \frac{\vec F}{q}");
INSERT INTO formulas VALUES("модуль напряженности электростатического поля точечного заряда","E = \frac{\vert q \vert}{&epsilon; r^2}");
INSERT INTO formulas VALUES("модуль напряженности электростатического поля, заряженного поля","E = k \frac{\vert q_ш \vert}{&epsilon; (R+r)^2}");
INSERT INTO formulas VALUES("принцип суперпозиции электрических полей","\vec E = \sum_{i = 1}^n \vec E_i");
INSERT INTO formulas VALUES("потенциал электростатического поля ","&phi; = \frac{W_p}{q}");
INSERT INTO formulas VALUES("потенциал электростатического поля точечного заряда","&phi; = \frac k{q}{&epsilon;r}");
INSERT INTO formulas VALUES("потенциал электростатического поля заряженного шара","&phi; = k \frac{q_ш}{&epsilon;(R+r)}");
INSERT INTO formulas VALUES("потенциал однородного электростатичесого поля ","&phi; = E \cdot d");
INSERT INTO formulas VALUES("потенциал электростатического поля системы зарядов","&phi; = \sum_{i = 1}^n &phi;_i");
INSERT INTO formulas VALUES("работа по перемещению зарядов в электрическом поле","A = q(&phi;_1 - &phi;_2) = qU");
INSERT INTO formulas VALUES("связь между модулем напряженности и напряжением для однородного электростатического поля","E = \frac{U}{d}");
INSERT INTO formulas VALUES("потенциальная энергия взаимоднйствия двух электрических зарядов","W = k \frac{q_1 \cdot q_2}{r}");
INSERT INTO formulas VALUES("электроемкость конденсатора","C = \frac qU");
INSERT INTO formulas VALUES("электроемкость плоского конденсатора ","C = \frac{&epsilon;_0 &epsilon; S}{d}");
INSERT INTO formulas VALUES("электроемкость паралельно соединенных конденсаторов ","C = \sum_{i = 1}^n C_i");
INSERT INTO formulas VALUES("величина, обратная электроемкости последовательно  соединенных конденсаторов","\frac 1C = \frac {qU}{2} = \frac{CU^2}{2} = \frac{q^2}{2C}");
INSERT INTO formulas VALUES("поверхностная плотность заряда","&sigma; = \frac qS");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("сила электрического тока","I = \frac qt");
INSERT INTO formulas VALUES("зависимость тока от заряда, концентрации, скорости, и площади поперечного сечения проводника","I = q_0 n&upsilon;S");
INSERT INTO formulas VALUES("модуль плотности электрического тока","j = \frac IS");
INSERT INTO formulas VALUES("закон Ома для участка цепи","I = \frac UR");
INSERT INTO formulas VALUES("зависимость сопротивления от рода вещества, длины и поперечного сечения проводника ","R = p \frac lS");
INSERT INTO formulas VALUES("зависимость сопротивления проводника о темературы","R = R_0(1+at)");
INSERT INTO formulas VALUES("сопротивление последовательно соединенных резисторов","R = \sum_{i=1}^n R_i");
INSERT INTO formulas VALUES("величина, обратная сопротивлению паралельно соединенных резисторов ","\frac 1R = \sum_{i = 1}^n \frac 1R_i");
INSERT INTO formulas VALUES("работа электрического тока","A = IUt = I^2 Rt = \frac UR^2t");
INSERT INTO formulas VALUES("мощность электрического тока","P = \frac At = IU = I^2 R = \frac{U^2}{R}");
INSERT INTO formulas VALUES("закон Джоуля-Ленца","Q = I^2 Rt");
INSERT INTO formulas VALUES("ЭДС","&Epsilon; = \frac {A_{cm}}{q}");
INSERT INTO formulas VALUES("закон Ома для полной цепи","I = \frac {E}{R+r}");
INSERT INTO formulas VALUES("сила тока в полной цепи с n последовательно соединенными одинаковыми элементами ЭДС","I = \frac{nE}{R+nr}");
INSERT INTO formulas VALUES("сила тока в неразветвленной части полной цепи с n паралельно соединенными одинаковыми элементами ЭДС","I = \frac{E}{R+\frac{r}{n}}");
INSERT INTO formulas VALUES("закон Фарадея для электролиза","m = kIT");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("модуль вектора магнитной индукции","\hat{A} = \frac {M_max}{IS} = \frac{F_max}{I \cdot \Delta l}");
INSERT INTO formulas VALUES("закон Ампера","F = IB\Delta l \sin \alpha");
INSERT INTO formulas VALUES("модуль слы Лоренца","F =\vert q \vert &upsilon; B \sin \alpha");
INSERT INTO formulas VALUES("имрульс заряженной частицы, движущейся по окружности в магнитном поле","m &upsilon; = qBR");
INSERT INTO formulas VALUES("магнитный поток","&Phi; = BS \cos \alpha");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("закон электромагнитной индукции","&Epsilon;_i = -\frac{\Delta \Phi}{\Delta t}");
INSERT INTO formulas VALUES("магнитнй поток через поверхность, ограниченную контуром","\Phi =  LI");
INSERT INTO formulas VALUES("максимальное значение ЭДС, возникающее в рамке, равномерно вращающейся в магнитном поле ","&epsilon;_m = \omega \Phi_m");
INSERT INTO formulas VALUES("ЭДС самоиндукции","&epsilon;_{is} = -\frac{\Delta \Phi}{\Delta t} = -L\frac{\Delta I}{\Delta t}");
INSERT INTO formulas VALUES("ЭДС индукции в движущихся проводниках","&epsilon; = B&upsilon;l \sin \alpha");
INSERT INTO formulas VALUES("электрический заряд, протекающий по замкнотому контуру, при изменении магнитного потока пронизывающего контур ","q = \frac{\Delta \Phi}{R}");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("зависимость заряда на обкладках конденсатора в колебательном контуре от времени","q = q_m \sin(\omega t +&phi;_0)");
INSERT INTO formulas VALUES("зависимость напряжения на обкладках конденсатора в колебательном контуре от времени","u = U_m \sin(\omega t +&phi;_0)");
INSERT INTO formulas VALUES("зависимость силы тока  в колебательном контуре от времени","i = I_m \cos(\omega t +&phi;_0)");
INSERT INTO formulas VALUES("максимальное значение силы тока при электромагнитных колебаниях","I_m = \omega q_m");
INSERT INTO formulas VALUES("период собственных колебаний колебательного круга(закон Томсона)","T = 2\pi \sqrt{LC}");
INSERT INTO formulas VALUES("энергия магнитного поля ","W_m = \frac{Li^2}{2}");
INSERT INTO formulas VALUES("полная энергия электромагнитного поля в колебательном контуре","\frac{q^2_m}{2C} = \frac{q^2}{2C} + \frac{Li^2}{2} = \frac{LI^2_m}{2}");
INSERT INTO formulas VALUES("действующее значение силы переменного электрического тока","I_{&sigma;} = \frac{U_m}{\sqrt 2}");
INSERT INTO formulas VALUES("действующее значение силы переменного напряжения","U_&sigma; = \frac{U_m}{\sqrt 2}");
INSERT INTO formulas VALUES("индукционное сопротивление ","X_L = \omega L");
INSERT INTO formulas VALUES("емкостное сопротивление","X_C = \frac{1}{\omega C}");
INSERT INTO formulas VALUES("полное сопротивление цепи переменного тока","Z = \sqrt{R^2 + (X_L - X_C)^2}");
INSERT INTO formulas VALUES("закон ома для участка цепи переменного тока","I = \frac UZ");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("закон преломления света","\frac{sin \alpha}{sin \beta} = \frac{n_2}{n_1} =");
INSERT INTO formulas VALUES("абсолютный показатель преломления","\frac{&upsilon;_1}{&upsilon;_2}");
INSERT INTO formulas VALUES("абсолютный показатель преломления","n = \frac c&upsilon;");
INSERT INTO formulas VALUES("формула тонкой линзы","\pm\frac 1F = \pm \frac 1f \pm \frac 1d");
INSERT INTO formulas VALUES("оптическая сила линзы","D = \frac 1F");
INSERT INTO formulas VALUES("линейное увеличение линзы","\Gamma = \frac Hh = \frac fd");
INSERT INTO formulas VALUES("условие интерференционного минимума","\Delta = (2k  + 1) \frac \lambda 2");
INSERT INTO formulas VALUES("условие интерференционного максимума","\Delta = k\lambda");
INSERT INTO formulas VALUES("условие максимумов дифракционной решетки","d sin &phi;  = k\lambda");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("релятивитский закон сложения скоростей","&upsilon; = \frac{&upsilon;_1 = &upsilon;_2}{1 +\frac{ &upsilon;_1 &upsilon;_2}{c^2}}");
INSERT INTO formulas VALUES("длина стержня в инерциальной системе, относительно которой он движется со скоростью","l =l_0 \sqrt{1 - \frac{&upsilon;^2}{c^2}}");
INSERT INTO formulas VALUES("интервал времени между двумя событиями в точке, которя движется относительо инерциальной системы со скоростью","&tau; = \frac{&tau;_0}{\sqrt{1- \frac{&upsilon;^2}{c^2}}}");
INSERT INTO formulas VALUES("зависимость массы тела от скорости ","m = \frac{m_0}{\sqrt{1- \frac{&upsilon;^2}{c^2}}}");
INSERT INTO formulas VALUES("связь между массой и энергией","E = mc^2");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("энергия фатона","E = hv");
INSERT INTO formulas VALUES("импульс фатона","p = mc = \frac{hv}{c}");
INSERT INTO formulas VALUES("уравнение Энштейна для фотоэффекта","hv = A + \frac{mv&upsilon;^2}{2}");
INSERT INTO formulas VALUES("работа выхода","A = h&nu;_min = h \frac{c}{\lambda_{кр}}");
INSERT INTO formulas VALUES("условие прекращения фотоэффекта","\frac{m&nu;^2}{2} = eU_з");
INSERT INTO formulas VALUES("2-й постулат Бора","h&nu; = E_п - E_m");
INSERT INTO formulas VALUES("длина волны де-Бройля","\lambda = \frac{h}{m&upsilon;}");
INSERT INTO formulas VALUES("закон радиоактивного распада","N = N_0 \cdot 2^{-\frac{t}{T}}");
INSERT INTO formulas VALUES("дефект масс","\Delta M = Zm_p +Nm_p -M_я");
INSERT INTO formulas VALUES("энергия связи атомных ядер","E_{св} = \Delta Mc^2");
INSERT INTO themes VALUES("Механика");
INSERT INTO themes VALUES("Кинематика криволинейного движения");
INSERT INTO themes VALUES("Динамика");
INSERT INTO themes VALUES("Статика");
INSERT INTO themes VALUES("Гидростаика");
INSERT INTO themes VALUES("Работа, энергия, мощность");
INSERT INTO themes VALUES("Колебания и волны");
INSERT INTO themes VALUES("Молекулярная физика");
INSERT INTO themes VALUES("Термодинамика");
INSERT INTO themes VALUES("Электростатика");
INSERT INTO themes VALUES("Постоянный элкетрический ток");
INSERT INTO themes VALUES("Магнитное поле электрического поля");
INSERT INTO themes VALUES("Электромагнитная индукция");
INSERT INTO themes VALUES("Элетромагнитные колебания");
INSERT INTO themes VALUES("Оптика");
INSERT INTO themes VALUES("Элементы теории относительности");
INSERT INTO themes VALUES("Квантовая физика, атомная и ядерная физика");
