INSERT INTO formulas VALUES("lata","s_x=x+x_0");
INSERT INTO formulas VALUES("la","\vec{&upsilon;}=\frac{\vec{s}}{t}");
INSERT INTO formulas VALUES("la","&upsilon;_{ср}=\frac{s}{t}");
INSERT INTO formulas VALUES("la","x=x_0+&upsilon;_xt");
INSERT INTO formulas VALUES("la","\vec{a}=\frac{\vec{&upsilon;}-{\vec{&upsilon;_0}}}{t}");
INSERT INTO formulas VALUES("la","\vec{&upsilon;}=\vec{&upsilon;_0}-\vec{a}t");
INSERT INTO formulas VALUES("la","\vec{s}=\frac{\vec{&upsilon;}+\vec{&upsilon;_0}}{2}t");
INSERT INTO formulas VALUES("la","\vec{s}=\vec{&upsilon;_0}t+\frac{\vec{a}t^2}{2}");
INSERT INTO formulas VALUES("la","s_x=\frac{&upsilon;_x^2-&upsilon;_{0x}^2}{2a_x}");
INSERT INTO formulas VALUES("la","x=x_0+&upsilon;_0t+\frac{at^2}{2}");
INSERT INTO formulas VALUES("la","T=\frac{t}{N}");
INSERT INTO formulas VALUES("la","&nu; = \frac{N}{t}");
INSERT INTO formulas VALUES("la","T = \frac{1}{&nu;}");
INSERT INTO formulas VALUES("la","&upsilon; = \frac{s}{t}");
INSERT INTO formulas VALUES("la","&upsilon; = \frac{2\pi r}{T}");
INSERT INTO formulas VALUES("la","&upsilon; = 2 \pi r &nu;");
INSERT INTO formulas VALUES("la","\omega = \frac{\varphi}{t}");
INSERT INTO formulas VALUES("la","\omega = 2 \pi &nu;");
INSERT INTO formulas VALUES("la","&nu; = \omega r");
INSERT INTO formulas VALUES("la","a = \frac{&upsilon;^2}{r}");
INSERT INTO formulas VALUES("la","a = \omega^2 r");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","\vec{a} = \frac{\vec{F_R}}{m}");
INSERT INTO formulas VALUES("la","\vec{F_1} = -\vec{F_2}");
INSERT INTO formulas VALUES("la","F_{тр} = &mu;N");
INSERT INTO formulas VALUES("la","F_{упр x} = -kx");
INSERT INTO formulas VALUES("la","\vec{F} = m\vec{g}");
INSERT INTO formulas VALUES("la","\vec{P} = m\vec{g}");
INSERT INTO formulas VALUES("la","\vec{P} = m(\vec{g}-\vec{a})");
INSERT INTO formulas VALUES("la","F = G\frac{m_1m_2}{r^2}");
INSERT INTO formulas VALUES("la","g = G\frac{M}{(R+h)^2}");
INSERT INTO formulas VALUES("la","&upsilon; = \sqrt{G\frac{M}{R}}");
INSERT INTO formulas VALUES("la","\vec{F}t = m\vec{&upsilon;}-m\vec{&upsilon;_0}");
INSERT INTO formulas VALUES("la","m_1\vec{&upsilon;_1} +m_2\vec{&upsilon;_2} = m_1\vec{{&upsilon;_1}^\prime} +m_2\vec{{&upsilon;_2}^\prime}");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","M = Fd");
INSERT INTO formulas VALUES("la","\sum_{i=1}^m \vec{F}_i = \vec{0}");
INSERT INTO formulas VALUES("la","\sum_{i=1}^n M_i = 0");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","&rho; = \frac{m}{V}");
INSERT INTO formulas VALUES("la","p = \frac{F}{S}");
INSERT INTO formulas VALUES("la","p = &rho;gh");
INSERT INTO formulas VALUES("la","F_{дно} = &rho;gHS_{дно}");
INSERT INTO formulas VALUES("la","F_{бок} = \frac{1}{2}&rho;gHS_{бок}");
INSERT INTO formulas VALUES("la","\frac{h_1}{h_2} = \frac{&rho;_1}{&rho;_2}");
INSERT INTO formulas VALUES("la","F_a = &rho;gV");
INSERT INTO formulas VALUES("la","F_2 = F_1 \frac{S_2}{S_1}");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","A = FS\cdot\cos\cdot\alpha");
INSERT INTO formulas VALUES("la","A = -F_{тр}s");
INSERT INTO formulas VALUES("la","A = mg(h_1 - h_2)");
INSERT INTO formulas VALUES("la","A = \frac{k}{2}(x_1^2 - x_2^2)");
INSERT INTO formulas VALUES("la","N = F &upsilon;");
INSERT INTO formulas VALUES("la","E_к = \frac{m&upsilon;^2}{2}");
INSERT INTO formulas VALUES("la","E_п = mgh");
INSERT INTO formulas VALUES("la","E_п = \frac{kx_2}{2}");
INSERT INTO formulas VALUES("la","E = E_п + E_к = const");
INSERT INTO formulas VALUES("la","A = \frac{m&upsilon;_2^2}{2} - \frac{m&upsilon;_1^2}{2}");
INSERT INTO formulas VALUES("la","&#951 = \frac{A_п}{A}");
INSERT INTO formulas VALUES("la","&#951 = \frac{N_п}{N}");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","F = k \frac{\vert q_1  \vert q_2}{&epsilon; r^2}");
INSERT INTO formulas VALUES("la","k = \frac{1}{4\pi &epsilon;_0} = 9 \cdot10^9 \frac{&Iota; \cdot \iota}{\vert E \vert ё^2}");
INSERT INTO formulas VALUES("la","\vec E = \frac{\vec F}{q}");
INSERT INTO formulas VALUES("la","E = \frac{\vert q \vert}{&epsilon; r^2}");
INSERT INTO formulas VALUES("la","E = k \frac{\vert q_ш \vert}{&epsilon; (R+r)^2}");
INSERT INTO formulas VALUES("la","\vec E = \sum_{i = 1}^n \vec E_i");
INSERT INTO formulas VALUES("la","&phi; = \frac{W_p}{q}");
INSERT INTO formulas VALUES("la","&phi; = \frac k{q}{&epsilon;r}");
INSERT INTO formulas VALUES("la","&phi; = k \frac{q_ш}{&epsilon;(R+r)}");
INSERT INTO formulas VALUES("la","&phi; = E \cdot d");
INSERT INTO formulas VALUES("la","&phi; = \sum_{i = 1}^n &phi;_i");
INSERT INTO formulas VALUES("la","A = q(&phi;_1 - &phi;_2) = qU");
INSERT INTO formulas VALUES("la","E = \frac{U}{d}");
INSERT INTO formulas VALUES("la","W = k \frac{q_1 \cdot q_2}{r}");
INSERT INTO formulas VALUES("la","C = \frac qU");
INSERT INTO formulas VALUES("la","C = \frac{&epsilon;_0 &epsilon; S}{d}");
INSERT INTO formulas VALUES("la","C = \sum_{i = 1}^n C_i");
INSERT INTO formulas VALUES("la","\frac 1C = \frac {qU}{2} = \frac{CU^2}{2} = \frac{q^2}{2C}");
INSERT INTO formulas VALUES("la","&sigma; = \frac qS");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","I = \frac qt");
INSERT INTO formulas VALUES("la","I = q_0 n&upsilon;S");
INSERT INTO formulas VALUES("la","j = \frac IS");
INSERT INTO formulas VALUES("la","I = \frac UR");
INSERT INTO formulas VALUES("la","R = p \frac lS");
INSERT INTO formulas VALUES("la","R = R_0(1+at)");
INSERT INTO formulas VALUES("la","R = \sum_{i=1}^n R_i");
INSERT INTO formulas VALUES("la","\frac 1R = \sum_{i = 1}^n \frac 1R_i");
INSERT INTO formulas VALUES("la","A = IUt = I^2 Rt = \frac UR t");
INSERT INTO formulas VALUES("la","&Epsilon; = \frac {A_{cm}}{q}");
INSERT INTO formulas VALUES("la","I = \frac {E}{R+r}");
INSERT INTO formulas VALUES("la","I = \frac{nE}{R+nr}");
INSERT INTO formulas VALUES("la","I = \frac{E}{R+\frac{r}{n}}");
INSERT INTO formulas VALUES("la","m = kIT");
INSERT INTO formulas VALUES("la","\hat{A} = \frac {M_max}{IS} = \frac{F_max}{I \cdot \Delta l}");
INSERT INTO formulas VALUES("la","F = IB\Delta l \sin \alpha");
INSERT INTO formulas VALUES("la","F =\vert q \vert &upsilon; B \sin \alpha");
INSERT INTO formulas VALUES("la","m &upsilon; = qBR");
INSERT INTO formulas VALUES("la","&Phi; = BS \cos \alpha");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","&epsilon;_i = -\frac{\Delta \Phi}{\Delta t}");
INSERT INTO formulas VALUES("la","\Phi =  LI");
INSERT INTO formulas VALUES("la","&epsilon;_m = \omega \Phi_m");
INSERT INTO formulas VALUES("la","&epsilon;_{is} = -\frac{\Delta \Phi}{\Delta t} = -L\frac{\Delta I}{\Delta t}");
INSERT INTO formulas VALUES("la","&epsilon; = B&upsilon;l \sin \alpha");
INSERT INTO formulas VALUES("la","q = \frac{\Delta \Phi}{R}");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","q = q_m \sin(\omega t +&phi;_0)");
INSERT INTO formulas VALUES("la","u = U_m \sin(\omega t +&phi;_0)");
INSERT INTO formulas VALUES("la","i = I_m \cos(\omega t +&phi;_0)");
INSERT INTO formulas VALUES("la","I_m = \omega q_m");
INSERT INTO formulas VALUES("la","T = 2\pi \sqrt{LC}");
INSERT INTO formulas VALUES("la","W_m = \frac{Li^2}{2}");
INSERT INTO formulas VALUES("la","\frac{q^2_m}{2C} = \frac{q^2}{2C} + \frac{Li^2}{2} = \frac{LI^2_m}{2}");
INSERT INTO formulas VALUES("la","I_{&sigma;} = \frac{U_m}{\sqrt 2}");
INSERT INTO formulas VALUES("la","U_&sigma; = \frac{U_m}{\sqrt 2}");
INSERT INTO formulas VALUES("la","X_L = \omega L");
INSERT INTO formulas VALUES("la","X_C = \frac{1}{\omega C}");
INSERT INTO formulas VALUES("la","Z = \sqrt{R^2 + (X_L - X_C)^2}");
INSERT INTO formulas VALUES("la","I = \frac UZ");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","\frac{sin \alpha}{sin \beta} = \frac{n_2}{n_1} =");
INSERT INTO formulas VALUES("la","\frac{&upsilon;_1}{&upsilon;_2}");
INSERT INTO formulas VALUES("la","n = \frac c&upsilon;");
INSERT INTO formulas VALUES("la","\pm\frac 1F = \pm \frac 1f \pm \frac 1d");
INSERT INTO formulas VALUES("la","D = \frac 1F");
INSERT INTO formulas VALUES("la","\Gamma = \frac Hh = \frac fd");
INSERT INTO formulas VALUES("la","\Delta = (2k  + 1) \frac \lambda 2");
INSERT INTO formulas VALUES("la","\Delta = k\lambda");
INSERT INTO formulas VALUES("la","d sin &phi;  = k\lambda");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","&upsilon; = \frac{&upsilon;_1 = &upsilon;_2}{1 +\frac{ &upsilon;_1 &upsilon;_2}{c^2}}");
INSERT INTO formulas VALUES("la","l =l_0 \sqrt{1 - \frac{&upsilon;^2}{c^2}}");
INSERT INTO formulas VALUES("la","&tau; = \frac{&tau;_0}{\sqrt{1- \frac{&upsilon;^2}{c^2}}}");
INSERT INTO formulas VALUES("la","m = \frac{m_0}{\sqrt{1- \frac{&upsilon;^2}{c^2}}}");
INSERT INTO formulas VALUES("la","E = mc^2");
INSERT INTO formulas VALUES("la");
INSERT INTO formulas VALUES("la","E = hv");
INSERT INTO formulas VALUES("la","p = mc = \frac{hv}{c}");
INSERT INTO formulas VALUES("la","hv = A + \frac{mv&upsilon;^2}{2}");
INSERT INTO formulas VALUES("la","A= h&nu;_min = h \frac{c}{\lambda_{кр}}");
INSERT INTO formulas VALUES("la","\frac{m&nu;^2}{2} = eU_з");
INSERT INTO formulas VALUES("la","h&nu; = E_п - E_m");
INSERT INTO formulas VALUES("la","\lambda = \frac{h}{m&upsilon;}");
INSERT INTO formulas VALUES("la","N = N_0 \cdot 2^{-\frac{t}{T}}");
INSERT INTO formulas VALUES("la","\Delta M = Zm_p +Nm_p -M_я");
INSERT INTO formulas VALUES("la","E_{св} = \Delta Mc^2");
INSERT INTO themes VALUES("Механика");
INSERT INTO themes VALUES("Кинематика криволинейного движения");
INSERT INTO themes VALUES("Динамика");
INSERT INTO themes VALUES("Статика");
INSERT INTO themes VALUES("Гидростаика");
INSERT INTO themes VALUES("Работа, энергия, мощность");
INSERT INTO themes VALUES("Колебания и волны");
INSERT INTO themes VALUES("Молекулярная физика");
INSERT INTO themes VALUES("Термодинамика");
INSERT INTO themes VALUES("Электростатика");
INSERT INTO themes VALUES("Постоянный элкетрический ток");
INSERT INTO themes VALUES("Магнитное поле электрического поля");
INSERT INTO themes VALUES("Электромагнитная индукция");
INSERT INTO themes VALUES("Элетромагнитные колебания");
INSERT INTO themes VALUES("Оптика");
INSERT INTO themes VALUES("Элементы теории относительности");
INSERT INTO themes VALUES("Квантовая физика, атомная и ядерная физика");
